server:
  port: 8901

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka, http://localhost:8762/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}

spring:
  application:
    name: product-service
